name: "Christopher Woodall"
markdown: kramdown
highlighter: rouge
description: "Embedded Systems Engineer, Musician and Rock Climber"
base_url: http://cwoodall.com
portfolio_tags: ['electronics', 'robotics', 'web_design','software', 'music', 'mechanical', 'other']
url: "http://cwoodall.com"
exclude:
  - "Makefile"
  - "Gemfile"
  - "Gemfile.lock"
  - ".gitignore"
  - "README.md"
  - ".ruby-version"
  - ".git"
  - "vendor"
  - ".env_vars"
gems: [jekyll-watch, jekyll-assets, jekyll-paginate]
